logging:
  config: classpath:logback-dev.xml

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #控制台打印 sql日志

# 数据库配置
spring:
  datasource:
    # 驱动名称
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 自定义用户名
    username: root
    # 自定义密码
    password: Demo_20250808
    # 数据库地址:jdbc:h2:mem:数据库名称(随意填写，会自动创建
    url: jdbc:mysql://novel-db:3306/novel_simple?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Tokyo
  sql:
    init:
      # 数据库平台内容配置项，主要有mysql、postgresql、oracle, h2等
      platform: mysql
      # 数据库初始脚本
      schema-locations: classpath:db/schema-mysql.sql
      # 数据库中表的初始脚本
      data-locations: classpath:db/data-h2.sql
      # mode: embedded  #如果用文件的模式 此处不会初始化sql
      mode: always  #- Spring Boot应用启动时始终执行数据库初始化
    # mode: embedded - 只初始化内存数据库，比如H2数据库
    # mode: never:  - 从不执行初始化数据库
  app:
    contentBase: http://book.wdllstudio.com:8585/

ideaflow:
  websocket:
    enable: true
    path: /ws
    sender-type: local